### PR TITLE
Fixes #7: Add BLT logo.

### LINKED ISSUE #7: Add BLT logo
As the title says: https://raw.githubusercontent.com/acquia/blt/9.1.x/blt-logo.png

I'll send a PR in a few minutes.

### PR DESCRIPTION
**Pull request by geerlingguy**

### CODE REVIEW

**Comment by theodorosploumis** [comment]
I will also add some new tools that I found on your list like VA#LAMP, outrigger etc that I didn't know about. Also "Acquia Dev" should be considered a tool too.

**Comment by geerlingguy** [comment]
@theodorosploumis - So glad I found this project—I was searching all over the place to find your old Google Sheet, had no idea you had refined it into this project. Let me know if there's anything else I can do to help out; also, one data point I really like to have is who or what entity is backing a particular project (helpful to know in discussions over purpose and maintenance).

**Comment by theodorosploumis** [comment]
That's a good point. At least each project has a source and there can be found the bakers. Some projects have no "specific" bakers and they are mostly community driven. So adding such info may be bad for some projects or taken as a "marketing".

(PS. I have just remembered that I could not add **Acquia Dev Desktop** when this list started because it is not open source.)

**Comment by geerlingguy** [comment]
@theodorosploumis do all projects have to be open source? It seems MAMP, WAMP, XAMPP, etc. might be worthy of inclusion—it would be best to maybe have a license field, and it could be indicated that the tool is or isn't open source, or if it's like GPLv2, MIT, BSD, etc.

**Comment by theodorosploumis** [comment]
I will consider this. But in this case the list will not be so "Drupal specific" but more wide. Acquia Dev Desktop is the only tool I think deserves to be on the list. Just created an issue (https://github.com/drupaltools/drupaltools.github.io/issues/9) to get more feedback for the licenses.

**Pull request merged**
